sudo: required
language: node_js
node_js:
  - '10'
  - '11'
  - '12'
matrix:
  fast_finish: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - git clone git://github.com/ladislav-zezula/StormLib.git
  - cd StormLib
  - cmake CMakeLists.txt -DBUILD_SHARED_LIBS=ON
  - sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

  - git clone git://github.com/Kanma/BLPConverter.git
  - cd BLPConverter
  - cmake CMakeLists.txt -DWITH_LIBRARY=YES
  - sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
env:
  - CXX=g++-4.8
script: npm test --coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
